const countryCodeMap = {
    US: 'Mỹ',
    DE: 'Đức',
    CH: 'Thụy Sĩ',
    MX: 'Mexico',
    CZ: 'Séc',
    KR: 'Hàn Quốc',
    EE: 'Estonia',
    JP: 'Nhật Bản',
    TW: 'Đài Loan',
    CN: 'Trung Quốc',
    AT: 'Áo',
    GB: 'Anh',
    FR: 'Pháp',
    SE: 'Thụy Điển',
    DK: 'Đan Mạch',
    ES: 'Tây Ban Nha',
    HU: 'Hungarry',
    ID: 'Ấn độ',
    IT: 'Italy',
    LT: 'Lithuania',
    MC: 'Monaco',
    AU: 'Australia',
    BE: 'Bỉ',
    BG: 'Bulgaria',
    BR: 'Brazil',
    HR: 'Croatia',
    MT: 'Malta',
    MY: 'Malaysia',
    NL: 'Hà Lan',
    PL: 'Ba Lan',
    RO: 'Romania',
    SG: 'Singapore',
    SI: 'Slovenia',
    VN: 'Việt Nam',
    TH: 'Thái Lan',
    SK: 'Slovakia',
    DO: 'Cộng hòa Dominican',
  };
  
  export const getCountryName = (code) => countryCodeMap[code] || code;
  